### PR TITLE
adding optional recursive diff.

### PR DESCRIPTION
**Pull request by flyinbutrs**
So I implemented it...  for my purpose, it works amazingly well. I't optional, you just have to do it as follows:

hash1.easy_diff(hash2, recurse_arrays: true)

It serves my purposes very well, what do you think?

### CODE REVIEW

**Comment by Blargel** [comment]
Please add some test cases into the test_data.yml file so I know what the intended functionality for your patch is. If you need help making sense of what's going on in there, let me know.

**Comment by Blargel** [comment]
Actually, I guess it isn't set up to have options passed in... Hmm. Well just write a normal spec test in easy_diff_spec.rb

**Comment by flyinbutrs** [comment]
Ok, working on it.

**Comment by Blargel** [comment]
I actually took a closer look at what you're trying here and I'm not sure I would like to pull this in for the same reasons as stated in issue #11. This works if you have equal length arrays with the hashes ordered the same in both arrays, but is too specific of a case for the purposes of this gem. It also breaks the merge/unmerge functionality.

**Pull request closed without merging**
