### PR TITLE
Allow merging and unmerging to succeed even if sorting fails

### PR DESCRIPTION
**Pull request by peakxu**
@Blargel, sorting can fail in some cases, see example in spec. Thought here is to allow merge to work but leave it unsorted.

### CODE REVIEW

**Comment by Blargel** [comment]
Thanks for the report. Since I've been getting a lot of activity on this gem recently, I'm going to rewrite my specs, add additional cases, and fix some other bugs I encounter as well.

**Comment by Blargel** [comment]
I'm honestly not a big fan of empty rescues. I'll try to find a better solution for this problem, but I may get lazy and merge this in anyways.

**Comment by peakxu** [comment]
This was meant as quick workaround to fix an issue I encountered during the day.

Will noodle on it a bit more as I don't like empty catches either.

Was curious about the rationale for sorting in the first place. Is it needed for correctness? If not, it might be faster without it if nothing else.

**Comment by Blargel** [comment]
It was a solution to a problem with merging from pull request #5.

**Comment by Blargel** [comment]
Oh, if you're asking why I'm sorting arrays in the first place... I don't remember anymore. This gem was written years ago as practice for programming in Ruby. It recently became unexpectedly popular so I need to try to remember my own intentions now.

**Comment by Blargel** [comment]
I'm removing sorting in my next release, which is finally going to be a major version bump. After going through everything again, it doesn't seem necessary and I think I only did it to make my poorly written tests pass when I was still a naive programmer.

**Pull request closed without merging**
